/**
 * WP-19G — manual external publish: pure helpers (no DB, no network, no GitHub).
 *
 * The clean public artifact is `RegistryProfile.payload` VERBATIM (already allowlist-built +
 * gate-passed). Held/internal context is OPERATOR-ONLY (`internalReview`) and is NEVER part of
 * the artifact. `mark-published` is gated on an explicit confirmed contentHash that must equal
 * the stored `payloadHash` — the app never claims a publication that wasn't human-confirmed.
 */

export const EXTERNAL_PUBLISH_WARNING =
  "This step creates material for a human PR. It does not publish automatically.";

export interface ExportPackage {
  warning: string;
  artifact: Record<string, unknown>; // = RegistryProfile.payload (clean entity-profile-v1.0)
  entitySlug: string;
  profileVersion: number;
  contentHash: string; // = RegistryProfile.payloadHash
  suggestedRegistryPath: string;
  source: { registryProfileId: string; truthPublishRecordId: string | null; canonVersion: string | null };
  prTitle: string;
  prDescription: string;
  validationChecklist: string[];
  internalReview: { heldClaimsExcluded: unknown[] }; // OPERATOR-ONLY — not in the artifact
}

export interface ExportInputs {
  registryProfileId: string;
  payload: Record<string, unknown>; // RegistryProfile.payload
  payloadHash: string; // RegistryProfile.payloadHash
  registryId: string; // RegistryProfile.registryId (= entitySlug)
  truthPublishRecordId: string | null;
  truthPublishRecordVersion: number | null;
  exportPayload: Record<string, unknown> | null; // TruthPublishRecord.exportPayload (the packet)
}

function asStr(v: unknown): string | null {
  return typeof v === "string" ? v : null;
}

export function buildExportPackage(input: ExportInputs): ExportPackage {
  const artifact = input.payload;
  const entitySlug = asStr(artifact.entitySlug) ?? input.registryId;
  const profileVersion =
    typeof artifact.profileVersion === "number" ? artifact.profileVersion : input.truthPublishRecordVersion ?? 0;
  const verification = (artifact.verification ?? {}) as Record<string, unknown>;
  const canonVersion = asStr(verification.canonVersion);
  const identity = (artifact.businessIdentifier ?? {}) as Record<string, unknown>;
  const commonName = asStr(identity.commonName) ?? asStr(identity.legalName) ?? entitySlug;
  const suggestedRegistryPath = `registry/${entitySlug}/profile.json`;
  const heldClaimsExcluded =
    input.exportPayload && Array.isArray(input.exportPayload.heldClaimsExcluded)
      ? (input.exportPayload.heldClaimsExcluded as unknown[])
      : [];

  const prTitle = `Add ${commonName} (${entitySlug}) verified profile`;
  const prDescription = [
    `Adds the verified public profile for **${commonName}** (\`${entitySlug}\`).`,
    "",
    `- Path: \`${suggestedRegistryPath}\``,
    `- profileVersion: ${profileVersion}`,
    `- contentHash: \`${input.payloadHash}\``,
    canonVersion ? `- Source Canon version: ${canonVersion}` : "",
    "- verification.status: claimed_verified (generated from a customer-approved Truth Canon).",
    "- No private notes, held claims, or internal evidence are included.",
    "",
    "Generated by Vizai-discovery (WP-19G manual export). Opened and merged by a human.",
  ]
    .filter(Boolean)
    .join("\n");

  const validationChecklist = [
    `Place the artifact at ${suggestedRegistryPath}.`,
    `Run locally: python tools/validation/validate-entity-profile.py ${suggestedRegistryPath}`,
    "Confirm business-registry CI (validate-registry.yml) passes: schema + clean-artifact + evidence + duplicates.",
    `After merge, recompute the Beacon contentHash of the merged profile.json and confirm it equals ${input.payloadHash}.`,
    "Then mark-published in the app with the PR URL and that confirmed contentHash.",
  ];

  return {
    warning: EXTERNAL_PUBLISH_WARNING,
    artifact,
    entitySlug,
    profileVersion,
    contentHash: input.payloadHash,
    suggestedRegistryPath,
    source: { registryProfileId: input.registryProfileId, truthPublishRecordId: input.truthPublishRecordId, canonVersion },
    prTitle,
    prDescription,
    validationChecklist,
    internalReview: { heldClaimsExcluded },
  };
}

// ── mark-published: gate + write shaper ──────────────────────────────────────

/** Throws unless the candidate can be marked published: present inputs, READY + DRAFT, and a matching hash. */
export function assertMarkPublishable(args: {
  registryProfileStatus: string;
  truthPublishStatus: string;
  payloadHash: string;
  confirmedContentHash: string;
  prUrl: string;
}): void {
  if (!args.prUrl) throw new Error("prUrl is required.");
  if (!args.confirmedContentHash) throw new Error("confirmedContentHash is required.");
  if (args.registryProfileStatus !== "READY") {
    throw new Error(`RegistryProfile must be READY to publish (got ${args.registryProfileStatus}).`);
  }
  if (args.truthPublishStatus !== "DRAFT") {
    throw new Error(`TruthPublishRecord must be DRAFT to publish (got ${args.truthPublishStatus}).`);
  }
  if (args.confirmedContentHash !== args.payloadHash) {
    throw new Error("contentHash mismatch — the confirmed hash does not match the prepared candidate.");
  }
}

export interface MarkPublishedWrites {
  registryProfile: { where: { id: string }; data: { status: "PUBLISHED" } };
  truthPublishRecord: {
    where: { id: string };
    data: { status: "PUBLISHED"; notes: string; exportPayload: Record<string, unknown> };
  };
}

export function buildMarkPublishedWrites(args: {
  registryProfileId: string;
  truthPublishRecordId: string;
  prUrl: string;
  confirmedContentHash: string;
  existingExportPayload: Record<string, unknown> | null;
  now: string; // ISO timestamp (caller supplies — keeps this pure)
}): MarkPublishedWrites {
  const externalPublish = {
    via: "manual-pr",
    prUrl: args.prUrl,
    confirmedContentHash: args.confirmedContentHash,
    publishedAt: args.now,
  };
  const exportPayload = { ...(args.existingExportPayload ?? {}), externalPublish };
  return {
    registryProfile: { where: { id: args.registryProfileId }, data: { status: "PUBLISHED" } },
    truthPublishRecord: {
      where: { id: args.truthPublishRecordId },
      data: {
        status: "PUBLISHED",
        notes: `Published to business-registry via manual PR ${args.prUrl} (confirmed ${args.now}).`,
        exportPayload,
      },
    },
  };
}
